[target]
default = "wasm32-unknown-unknown"

[serve]
# Expose loopback + host IP to allow local development testing via mobile phone
address = "0.0.0.0"
# Required in order to receive 404s for missing assets, which is what Bevy expects.
no_spa = true
# Open a browser tab once the initial build is complete.
# TODO: This isn't working from within Docker
# open = true